version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      # Use postgres/example user/password credentials
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    # entrypoint: /app/initdb.sh

  app:
    build: .
    entrypoint: python3 /app/run.py
    volumes:
      - .:/app

